export const hookLines = [
  'Looking very mindful and demure',
  'Aura for aura',
  'With my Otaku bestie',
  'I am a chosen DevFest who are you?',
  'To unlock my domain expansion',
  "And that's on period ",
  'Because you know they Neva Play',
  'With maximum steeze and composure',
  'Anyway, fishpieeeeeee una to do o',
  'Info leyan finfo',
  'Hold on, let them cook!',
  "I'm sat!",
  'Oya oya, you don catch me',
];
